/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LaunchStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'ended' : IDL.Null,
});
export const Time = IDL.Int;
export const Launch = IDL.Record({
  'id' : IDL.Nat,
  'status' : LaunchStatus,
  'ticker' : IDL.Text,
  'projectName' : IDL.Text,
  'createdAt' : Time,
  'fundraiseGoal' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'totalSupply' : IDL.Opt(IDL.Nat),
  'launchDate' : IDL.Opt(IDL.Text),
  'priceInDoge' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFirstLaunch' : IDL.Func([], [], []),
  'createLaunch' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Opt(IDL.Text),
        LaunchStatus,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteLaunch' : IDL.Func([IDL.Nat], [], []),
  'getAllLaunches' : IDL.Func([], [IDL.Vec(Launch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLaunchById' : IDL.Func([IDL.Nat], [Launch], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLaunch' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Opt(IDL.Text),
        LaunchStatus,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LaunchStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'ended' : IDL.Null,
  });
  const Time = IDL.Int;
  const Launch = IDL.Record({
    'id' : IDL.Nat,
    'status' : LaunchStatus,
    'ticker' : IDL.Text,
    'projectName' : IDL.Text,
    'createdAt' : Time,
    'fundraiseGoal' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'totalSupply' : IDL.Opt(IDL.Nat),
    'launchDate' : IDL.Opt(IDL.Text),
    'priceInDoge' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFirstLaunch' : IDL.Func([], [], []),
    'createLaunch' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Opt(IDL.Text),
          LaunchStatus,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteLaunch' : IDL.Func([IDL.Nat], [], []),
    'getAllLaunches' : IDL.Func([], [IDL.Vec(Launch)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLaunchById' : IDL.Func([IDL.Nat], [Launch], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLaunch' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Opt(IDL.Text),
          LaunchStatus,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };